#!/usr/bin/python

import argparse
import subprocess

p = argparse.ArgumentParser()
p.add_argument('filters', metavar='PATTERN', nargs='*',
               help="Filter results with PATTERN")

args = p.parse_args()
if args.filters:
    grepchain = ' | '.join(["grep -i \"%s\"" % f for f in args.filters])
    subprocess.call(
        "cat players.csv | %s | head -n 20 | column -t -s," % grepchain,
        shell=True)
else:
    subprocess.call(
        "head -n 20 players.csv | column -t -s,",
        shell=True)
