#!/usr/bin/python
import re

urls = ['http://www.fantasypros.com/nfl/adp/overall.php']

def players(soup):

    for name_link in soup.find_all('a', href=re.compile('^/nfl/(players|teams/.*-defense)')):
        try:
            name = name_link.text

            if name.endswith('DST'):
                team = name[0:-4]
                name = "%s DST" % team
            else:
                next_smalls = name_link.find_next_siblings('small')
                team_small = next_smalls[0] if next_smalls else None
                if not team_small:
                    continue
                team = strip_nonteam(team_small.text)

            name_td = name_link.find_parent('td')
            position_td =  name_td.find_next_sibling('td')
            position = strip_position_rank(position_td.string)

            rank = position_td.find_next_siblings('td')[-1].string

            yield {
                'name': name,
                'team': team,
                'position': position,
                'rank': rank
            }

        except Exception, e:
            base.debug(e)

def strip_nonteam(val):
    m = re.search('([A-Z]*)', val)
    if m:
        return m.groups()[0]
    else:
        return val

def strip_position_rank(position):
    m = re.search('([^0-9]+)[0-9]*', position)
    if m:
        return m.groups()[0]
    else:
        return position

if __name__ == '__main__':
    import base
    base.run_soup('fantasypros-adp', urls, players)
