#!/usr/bin/python
import re

urls = [
    'http://games.espn.com/ffl/tools/projections',
    'http://games.espn.com/ffl/tools/projections?startIndex=40',
    'http://games.espn.com/ffl/tools/projections?startIndex=80',
    'http://games.espn.com/ffl/tools/projections?startIndex=120',
    'http://games.espn.com/ffl/tools/projections?startIndex=160',
    'http://games.espn.com/ffl/tools/projections?startIndex=200',
]

def players(soup):

    for name_link in soup.find_all('a', playerid=re.compile("\d+")):
        try:
            if name_link.string is None:
                continue

            rank = int(name_link.parent.previousSibling.string)
            name = name_link.string
            if name.endswith('D/ST'):
                team = name.split(' ')[0]
                pos = "DST"
            else:
                team, pos = name_link.nextSibling.string[2:].split(u'\xa0')[:2]

            yield {
                'name': name,
                'team': team,
                'position': pos,
                'rank': rank
            }

        except Exception, e:
            raise

if __name__ == '__main__':
    import base
    base.run_soup('espn-ecr', urls, players)
