#!/usr/bin/python
import re

urls = ['http://www.fantasypros.com/nfl/rankings/consensus-cheatsheets.php']

def players(soup):
    for name_span in soup.find_all('span', class_='full-name'):
        try:
            name = name_span.text
            name_link = name_span.parent
            maybe_dst = re.match('.+ \((.+)\)', name)
            if maybe_dst:
                team = maybe_dst.group(1)
                name = "%s DST" % team
                position = "DST"
            else:
                team_small = name_link.find_next_sibling('small')
                team = strip_nonteam(team_small.text)
                name_td = name_link.find_parent('td')
                position_td =  name_td.find_next_sibling('td')
                position = strip_position_rank(position_td.string)
            rank = position_td.find_next_siblings('td')[3].string
            yield {
                'name': name,
                'team': team,
                'position': position,
                'rank': rank
            }
        except Exception, e:
            base.debug(e)

def dst_name_team(name):
    m = re.search('(.*) Defense', name)
    if m:
        team = m.groups()[0]
        name = '%s DST' % team
        return name, team
    else:
        return None

def strip_nonteam(val):
    m = re.search('([A-Z]*)', val)
    if m:
        return m.groups()[0]
    else:
        return val

def strip_position_rank(position):
    m = re.search('([^0-9]+)[0-9]*', position)
    if m:
        return m.groups()[0]
    else:
        return position

if __name__ == '__main__':
    import base
    base.run_soup('fantasypros-ecr', urls, players)
