#!/usr/bin/python
import re

urls = ['http://www.espn.com/fantasy/football/story/_/id/16287927/2016-fantasy-football-rankings-top-300']

def players(soup):

    name_link_re = re.compile('^http://www.espn.com/nfl/player|^/nfl/team/')

    for name_link in soup.find_all('a', href=name_link_re):

        if is_category_link(name_link):
            continue

        try:
            # name
            name = name_link.string
            name_cell = name_link.parent

            # position
            position_cell = name_cell.next_sibling
            position = position_cell.text.strip()

            # team
            team_cell = position_cell.next_sibling
            team = team_cell.text.strip()

            # rank
            rank = name_cell.text.split()[0][:-1]

            # get team from name if DEF
            if position == 'DST':
                team = name
                position = 'DST'

            yield {
                'name': name,
                'team': team,
                'position': position,
                'rank': rank
            }

        except Exception, e:
            raise

def is_category_link(link):
    return link.parent.attrs.get('class') == ['category-link']

if __name__ == '__main__':
    import base
    base.run_soup('espn-ecr', urls, players)
