#!/usr/bin/python
import re

urls = ['http://espn.go.com/fantasy/football/story/_/id/12866396/top-300-rankings-2015']

def players(soup):

    name_link_re = re.compile('^http://espn.go.com/nfl/player|^/nfl/team/')

    for name_link in soup.find_all('a', href=name_link_re):

        if is_category_link(name_link):
            continue

        try:
            # name
            name = name_link.string
            name_cell = name_link.parent

            # team
            team_cell = name_cell.next_sibling
            team = team_cell.string.strip()

            # rank
            rank_cell = name_link.previous_sibling
            rank = rank_cell.string.strip()[:-1]
            
            # position
            position_cell = name_link.next_sibling
            position = position_cell.string.strip()[2:]

            # get team from name if DEF
            if position == 'DST':
                team = name
                position = 'DST'

            yield {
                'name': name,
                'team': team,
                'position': position,
                'rank': rank
            }

        except Exception, e:
            raise

def is_category_link(link):
    return link.parent.attrs.get('class') == ['category-link']

if __name__ == '__main__':
    import base
    base.run_soup('espntop', urls, players)
