teams = {
    'ARIZONA CARDINALS': 'AZ',
    'BALTIMORE RAVENS': 'BAL',
    'BUFFALO BILLS': 'BUF',
    'CAROLINA PANTHERS': 'CAR',
    'CINCINNATI BENGALS': 'CIN',
    'DENVER BRONCOS': 'DEN',
    'HOUSTON TEXANS': 'HOU',
    'KANSAS CITY CHIEFS': 'KC',
    'NEW ENGLAND PATRIOTS': 'NE',
    'NEW ORLEANS SAINTS': 'NO',
    'SAN FRANCISCO 49ERS': 'SF',
    'SEATTLE SEAHAWKS': 'SEA',
    'ST. LOUIS RAMS': 'STL',
    'TAMPA BAY BUCCANEERS': 'TB',
}

positions = {
}
